// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAE5EuSs3nHWWUnSlWwiF6qDMlWnsEtMWg',
    appId: '1:358064046198:web:06037be97f3e248e299f57',
    messagingSenderId: '358064046198',
    projectId: 'audio-d9a8d',
    authDomain: 'audio-d9a8d.firebaseapp.com',
    storageBucket: 'audio-d9a8d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT1PzeL8Pz-ztxzSDPV2sN6pkOkSCgROg',
    appId: '1:358064046198:android:aa9aac87b8ef45b4299f57',
    messagingSenderId: '358064046198',
    projectId: 'audio-d9a8d',
    storageBucket: 'audio-d9a8d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4pa76k-RsqYOj__5_9WXTuUiom2bipRg',
    appId: '1:358064046198:ios:619cdfc9f847c8a7299f57',
    messagingSenderId: '358064046198',
    projectId: 'audio-d9a8d',
    storageBucket: 'audio-d9a8d.firebasestorage.app',
    iosClientId: '358064046198-k7d60avoi3h4gff53hc447l19fg82c9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.audioApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4pa76k-RsqYOj__5_9WXTuUiom2bipRg',
    appId: '1:358064046198:ios:619cdfc9f847c8a7299f57',
    messagingSenderId: '358064046198',
    projectId: 'audio-d9a8d',
    storageBucket: 'audio-d9a8d.firebasestorage.app',
    iosClientId: '358064046198-k7d60avoi3h4gff53hc447l19fg82c9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.audioApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAE5EuSs3nHWWUnSlWwiF6qDMlWnsEtMWg',
    appId: '1:358064046198:web:d8f947868c100cb4299f57',
    messagingSenderId: '358064046198',
    projectId: 'audio-d9a8d',
    authDomain: 'audio-d9a8d.firebaseapp.com',
    storageBucket: 'audio-d9a8d.firebasestorage.app',
  );
}
